	.ORIG X3000
	
;	LOAD THE PROMPT AND PRINT IT TO THE SCREEN

	LEA R0, PROMPT
	PUTS

;	READ THE INPUTS AND STORE THEM IN MEMORY

	AND R2, R2, #0
	LD R4, ENTER
	LEA R1, STORE
MORE	GETC
	OUT
	ADD R3, R0, R4 ; CHECK TO SEE IF THE INPUT CHARACTER IS ENTER KEY
	BRZ DONE	
	STR R0, R1, #0
	ADD R1, R1, #1
	BRNZP MORE
DONE	STR R2, R1, #0 ; STILL HAVE TO ENTER NULL TERMINATOR


;	INTIALIZE ALL THE POINTERS

	LD R1, FIRST 	; R1 NOW CONTAINS X3300
	LDR R2, R1, #0 	; R2 CONTAINS THE POINTER OF THE VERY FIRST NODE
NEXT1	ADD R2, R2, #0 	; 
	BRZ NAH 	; IF THE CURRENT NODE IS NULL, THEN WE HAVE TO PRINT NOT REGISTERED
	LDR R4, R2, #0 	; R4 IS POINTER OF NEXT NODE
	ST R4, NXTNODE	; PUT THAT IN MEMORY
	LEA R1, STORE	; R1 POINTS TO VERY FIRST LETTER OF LAST NAME THAT USER TYPED IN
	ADD R2, R2, #1	; 
	LDR R3, R2, #0	; R3 POINTS TO VERY FIRST LETTER OF LAST NAME IN DIRECTORY
	ADD R2, R2, #1 	;
	LDR R4, R2, #0	;
	ST R4, UNI 	; STORE THE POINTER OF THE VERY FIRST NUMBER OF THE UNIQUE NUMBER


; 	COMPARE ROUTINE

	AND R6, R6, #0	;	
CHECK 	LDR R4, R1, #0	; LOAD THE TYPED LETTER INTO R4
	LDR R5, R3, #0	; LOAD THE DIRECTORY LETTER INTO R5
	BRZ NULL 	;
	ADD R4, R4, #0	;
	BRZ NOMATCH 	; 
	NOT R4, R4 	;
	ADD R4, R4, #1	;
	ADD R0, R4, R5	; SUBTRACT ONE FROM THE OTHER
	BRZ MATCH	;
	BR NOMATCH	;
	
NULL	ADD R4, R4, #0 	;
	BRZ FINAL	;

NOMATCH ADD R6, R6, #0 	;
	LD R2, NXTNODE	;
	BR NEXT1 	;

MATCH 	ADD R1, R1, #1	;
	ADD R3, R3, #1	;
	BR CHECK 	; THE CURRENT LETTERS MATCH, CHECK THE NEXT ONE

FINAL	ADD R6, R6, #1 	; THE STRINGS MATCH!
	BR OUTT		;


;	NOW EITHER PRINT THE UNIQUE NUMBER OR PRINT NOT REGISTERED

OUTT	ADD R6, R6, #0	;
	BRZ NAH		; R6 IS ZERO, SO THEY DONT MATCH, JUMP
	LD R0, UNI	; LOAD THE FIRST LOCATION OF THE FIRST LETTER IN R0
	PUTS 		; 
	BR STOP		;

NAH	LEA R0, NONE 	;
	PUTS	


STOP	HALT

PROMPT	.STRINGZ "Type a last name and press Enter:"
ENTER	.FILL x-0A
STORE	.BLKW 16
FIRST	.FILL x3300
NXTNODE	.BLKW 1
UNI	.BLKW 1
NONE	.STRINGZ "Not Registered"

	.END